---
- name: Configure System
  hosts: local
  connection: local
  become: true
  roles:
    - role: common
      tags: [common]
    - role: gnome
      become: false
      tags: [gnome]
    - role: aws
      tags: [aws]
